# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-02 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180725_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='member_file/%Y/%m/%d/')),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
