# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-01 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20181002_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='admin_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
