# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-03 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_organization_admin_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
    ]
