# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-15 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20181003_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='insufficient_benefit_credits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='salary_adjustment',
            field=models.BooleanField(default=False),
        ),
    ]
