# Generated by Django 3.0.8 on 2020-12-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20201216_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='text_block_1',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='text_block_2',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='text_block_3',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
    ]
