# Generated by Django 3.0.8 on 2021-03-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20201224_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='enrollment_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='text_block_4',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
    ]
