# Generated by Django 3.0.8 on 2021-07-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20210326_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
